# _base_: 
#   - base/visualization/clearml.yml

# Setup
env_cfg: {}
train_cfg:
  by_epoch: &by_epoch True
  max_epochs: &max_epochs 50
  val_interval: 50
val_cfg: {}
find_unused_parameters: True

# Dataset and loaders
train_dataloader:
  batch_size: 10
  num_workers: 8 
  pin_memory: true
  persistent_workers: true
  dataset: 
    type: SOD_TRAIN
    data_dir: /root/autodl-tmp/dataset/TrainDataset/
    depth_dir: depth
    split: train
  sampler:
    type: DefaultSampler
    shuffle: True
val_dataloader:
  batch_size: 1
  num_workers: 8
  dataset: 
    type: SOD_TEST
    data_dir: /root/autodl-tmp/dataset/TestDataset/NJU2K/
    depth_dir: depth
    split: val
  sampler:
    type: DefaultSampler
    shuffle: False

# Model
model:
  type: cod
  win_size: 22
  filter_ratio: 0.9
  using_sam: True
  using_depth: True
  finetune: True
  binary_thresh: 0.2
  pretrain_sam: output/train_60epo_lr_1e-4/epoch_60.pth
  head: 
    type: mmseg.models.decode_heads.SegformerHead
    in_channels: [256, 512, 1024, 2048]
    channels: 256
    num_classes: 1
    in_index: [0,1,2,3]
# Optimization
optim_wrapper:
  type: AmpOptimWrapper
  optimizer:
    type: AdamW
    lr: 0.0005
    weight_decay: 0.1
  paramwise_cfg: 
    bypass_duplicate: True
    custom_keys: 
      hitnet.backbone:
        lr_mult: 0.2
      hitnet.backbone.prompt_encoder.encoder2.downsample_layers:
        lr_mult: 0.02
      hitnet.backbone.prompt_encoder.encoder2.stages.0:
        lr_mult: 0.02
      hitnet.backbone.prompt_encoder.encoder2.stages.1:
        lr_mult: 0.02
      hitnet.backbone.prompt_encoder.encoder2.stages.2:
        lr_mult: 0.02
      hitnet.backbone.prompt_encoder.encoder2.stages.3:
        lr_mult: 0.02

param_scheduler:
  type: CosineAnnealingLR
  by_epoch: *by_epoch
  T_max: *max_epochs


# Evaluation
val_evaluator:
  - type: Emeasure
  - type: Fmeasure
  - type: Smeasure
  - type: MAE

# Hooks
default_hooks:
  logger:
    type: LoggerHook
    interval: 5
    ignore_last: false
  checkpoint:
    type: CheckpointHook
    by_epoch: *by_epoch
    interval: 1

custom_hooks:
  -
    type: our_init
